### ISSUE TITLE
Would a debug Toast be a good feature?¿

### ISSUE THREAD

**Issue by iagocanalejas** [GrenderG/Toasty#10]
I can PR if you want the feature in your lib

**Comment by GrenderG** [comment]
What do you mean exactly with "debug" Toast and why would anyone want to use a Toast for debug instead of the Logcat?

Anyway thanks for your suggestion, you can provide a screenshot of what do you mean with a debug Toast.

**Comment by iagocanalejas** [comment]
Don't know if really a useful feature for other people. I use to go with toasts for test some behaviours and i mean something like:
```java
Toasty.debug(...);
``` 
instead of
```java
if (BuildConfig.BUILD_TYPE.equals(DEBUG)) {
     Toasty.info(...);
}
```

**Comment by GrenderG** [comment]
Toasts are not intended to do so IMO, for the moment I won't add this feature.

Thanks anyway, mate.
