### ISSUE TITLE
Changing colors globally

### ISSUE THREAD

**Issue by conacelelena** [GrenderG/Toasty#101]
Hello!

Is there a way to change the default colors for success, error and info?

All the best,
Cristina

**Comment by GrenderG** [comment]
Yes! You can override [these values](https://github.com/GrenderG/Toasty/blob/master/toasty/src/main/res/values/colors.xml).

**Comment by conacelelena** [comment]
I am new to Android development and I don't know where to find this file inside my project. Can you help me? I have added the library to gradle.build, but I don't see the files locally.

Cristina

**Comment by GrenderG** [comment]
You can just create a file called `colors.xml` inside your `res` folder and override [these values](https://github.com/GrenderG/Toasty/blob/master/toasty/src/main/res/values/colors.xml) by creating entries with the same name as in Toasty but with different values.

For example, if you put this in your `colors.xml` file,
```xml
<color name="errorColor">#D500FF</color>
```
error Toasts will be purple.

**Comment by conacelelena** [comment]
Thank you for your answer! This works :)
