### ISSUE TITLE
Conflict with com.android.support:appcompat-v7:28.0.0

### ISSUE THREAD

**Issue by doublemarkpro** [GrenderG/Toasty#102]
With adding 
implementation 'com.github.GrenderG:Toasty:1.4.0'
implementation 'com.android.support:appcompat-v7:28.0.0-alpha1'
implementation 'com.android.support.constraint:constraint-layout:1.1.3'
implementation 'com.android.support:design:28.0.0-alpha1'

the preview of Android Studio Layout will not work but only show a gray pic.

After comment implementation 'com.github.GrenderG:Toasty:1.4.0' the preview turns good.
Have tried v7:28.0.0  ervery version of that.

Android Studio 3.1.4

**Comment by sami286** [comment]
Thats because you are usaing two different versions of the same library in your project: _28.0.0-alpha1_ and _28.0.0_ (the one Toasty uses).
Upgrading all _28.0.0-alpha1_ versions to _28.0.0_ should fix that!
