### ISSUE TITLE
Error - Urgent

### ISSUE THREAD

**Issue by LaTecnologia24** [GrenderG/Toasty#104]
Before Update to v1.4 with the 1.2 this code working perfect:

```
Toasty.custom(getApplicationContext(), "WiFi", getResources().getDrawable(R.drawable.ic_wifi_black_24dp),
                    getResources().getColor(R.color.md_red_700), Toast.LENGTH_SHORT, true, true).show();
```

Now report error:

`Cannot resolve method 'custom(android.content.Context, java.lang.String, android.graphics.drawable.Drawable, int, int, boolean, boolean)'`

With 1.2 and 1.3 same code work...

**Comment by GrenderG** [comment]
You now need to use `DrawableRes` instead of `DrawableInt`, and, in version `1.4.1`, you need to use `ColorRes` instead of `ColorInt` too, it's easier for developers if Toasty handles directly that.
```java
Toasty.custom(getApplicationContext(), "WiFi", R.drawable.ic_wifi_black_24dp, 
        R.color.md_red_700, Toast.LENGTH_SHORT, true, true).show();
```
