### ISSUE TITLE
could not resolve Toasty 1.2.5 from  jitpack.io

### ISSUE THREAD

**Issue by kayhanakbay** [GrenderG/Toasty#111]
compile 'com.github.GrenderG:Toasty:1.2.5'  not resolved from jitpack..  

https://jitpack.io/com/github/GrenderG/Toasty/1.2.5/Toasty-1.2.5.aar  not return .aar file !

**Comment by GrenderG** [comment]
## Prerequisites

Add this in your root `build.gradle` file (**not** your module `build.gradle` file):

```gradle
allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}
```

## Dependency

Add this to your module's `build.gradle` file (make sure the version matches the JitPack badge above):

```gradle
dependencies {
	...
	implementation 'com.github.GrenderG:Toasty:1.4.2'
}
```
