### ISSUE TITLE
Change Toast Color Feature

### ISSUE THREAD

**Issue by searchy2** [GrenderG/Toasty#12]
Wow, these toasts look amazing! A definite upgrade to the system default toast messages. I have a quick question about the toast features. Is it possible to customize the color of a toast message? I see that there are different types of toast notifications such as Red for error, Green for success, and Grey for Normal. Would it not be easier to just have one toast that can be customized with the desired color?

**Comment by GrenderG** [comment]
You can customize a Toast with the `custom()` method:

```java
Toasty.custom(yourContext, "I'm a custom Toast", yourIconDrawable, textColor, tintColor, duration, withIcon, true).show();
```

Thanks. ;)

**Comment by searchy2** [comment]
@GrenderG Thank you so much! :clap:

**Comment by vomitous** [comment]
kudos
