### ISSUE TITLE
Toast will show twice

### ISSUE THREAD

**Issue by a173012907** [GrenderG/Toasty#123]
when will use there medthod:
Toast.error()
Toast.success()

it will extra show a Toast.normal()

**Comment by GrenderG** [comment]
Can you share the specific piece of code and provide a small recording? Also, have you tried in more devices?

**Comment by a173012907** [comment]
we use code versoin is 1.3.0
```
  val message = ExceptionMessage.getMessage(error)
   KitUtil.showToast(message)
```
