### ISSUE TITLE
Any way to anchor the toast to a view?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [GrenderG/Toasty#14]
So that it will appear near it, but without overlapping it?

**Comment by GrenderG** [comment]
No, but you can achieve that behaviour by playing with <a href="https://developer.android.com/reference/android/widget/Toast.html#setGravity(int, int, int)">the Toast's gravity</a> and obtaining the View's X and Y.

**Comment by AndroidDeveloperLB** [comment]
Can you please show how to do it well?
I've made a post about it here:
http://stackoverflow.com/q/42783387/878126

**Comment by GrenderG** [comment]
@AndroidDeveloperLB have you achieved what you needed? I think I'm gonna close this issue since it's not directly related to Toasty, but I kept it opened in case someone helped you.

**Comment by AndroidDeveloperLB** [comment]
No, I haven't.
I asked this because it's about toasts, and this library is about toasts.
Also, Google has recently added something like a toast, called tooltip. I think this should work like what I wrote. Not sure.

**Comment by GrenderG** [comment]
@AndroidDeveloperLB Yeah I know, I think so too. Is there any official implementation of Tooltips at this moment?

**Comment by AndroidDeveloperLB** [comment]
I haven't found it
