### ISSUE TITLE
Apps using Toasty

### ISSUE THREAD

**Issue by javimar** [GrenderG/Toasty#143]
Hi, really like your library. I am using it in my swimmer app.
https://play.google.com/store/apps/details?id=eu.javimar.myswim

Best!

**Comment by javimar** [comment]
Just realized that it is not featured in app that use Toasty. Do you need anything else?

**Comment by GrenderG** [comment]
> Just realized that it is not featured in app that use Toasty. Do you need anything else?

Hello! Sorry for the late reply, I totally forgot to add it. A PR would be appreciated.

**Comment by javimar** [comment]
Hi, exactly what you mean with PR?

**Comment by GrenderG** [comment]
A Pull Request where you add your app.
