### ISSUE TITLE
I love Toasty

### ISSUE THREAD

**Issue by teoCoding** [GrenderG/Toasty#159]
I'm using Toasty in my app!

Birthday Reminder
https://play.google.com/store/apps/details?id=com.apputilose.teo.birthdayremember

**Comment by teoCoding** [comment]
> great job!

Thank You 😀🙏🏻

**Comment by Canoir** [comment]
Hi,
Please remove or close your issue cause this is ads, not an issue!

**Comment by teoCoding** [comment]
This is doesn't want to be ads:
According with readme:

Apps using Toasty

Want to be here? Open an issue or make a pull request.

**Comment by teoCoding** [comment]
> Hi,
> Please remove or close your issue cause this is ads, not an issue!

This is doesn't want to be ads:
According with readme:

Apps using Toasty

Want to be here? Open an issue or make a pull request.

**Comment by Istiakshovon** [comment]
@teoCoding  I think you should close it. Since it's not issue.. Other people might get distracted for the issue...
