### ISSUE TITLE
Failed to resolve: com.github.GrenderG:Toasty:1.1.4

### ISSUE THREAD

**Issue by lifeisdream** [GrenderG/Toasty#17]
Gradle can't find the lib
I add compile 
`'com.github.GrenderG:Toasty:1.1.4' ` into buil.gradle (app) with the rest of the lib, but get `Failed to resolve: com.github.GrenderG:Toasty:1.1.4` error message. 

ANy help?

**Comment by lifeisdream** [comment]
Sorry. my fault, forget to add maven { url "https://jitpack.io" }. 
great lib! thanks!

**Comment by GrenderG** [comment]
Glad you solve it. :)
