### ISSUE TITLE
What controls toast text padding?

### ISSUE THREAD

**Issue by searchy2** [GrenderG/Toasty#18]
Hi @GrenderG , thanks for the great library!
I have a question about how the text padding for Toasty is set. Usually, text in Toasty has a 16-20dp left right margin. However, when I am using the library in a fullscreen activity, the text padding disappears. What is setting the toast's text padding? 

P.S. I am currently adding spaces around my toast messages like "    Toast Message    " to simulate padding. It works great :D

**Comment by GrenderG** [comment]
Mmm, that's so weird, can you provide example images of what's happening? The padding belongs to the [original Toast 9patch image](https://github.com/GrenderG/Toasty/blob/master/toasty/src/main/res/drawable-hdpi/toast_frame.9.png).

**Comment by searchy2** [comment]
![screenshot_2017-04-13-13-28-33](https://cloud.githubusercontent.com/assets/19896174/25018727/b3fe1bd6-204d-11e7-94ca-266235a372f3.png)
![screenshot_2017-04-13-13-28-54](https://cloud.githubusercontent.com/assets/19896174/25018731/b556a30e-204d-11e7-8573-f0e7d46e7381.png)

**Comment by GrenderG** [comment]
Which Android version / device are u using?

**Comment by searchy2** [comment]
I have tested this in my emulator and actual device. So far, I have tested it in 7.0, 6.0. I am going to try to reproduce the problem in the app where the toast padding is correct to see if my theory that the activity theme has something to do with the padding.

**Comment by searchy2** [comment]
Got it, found the culprit :fireworks: 
It appears that setting fitsSystemWindows to true eliminates the padding.
`<item name="android:fitsSystemWindows">true</item>`
Any idea the reason behind this?

**Comment by GrenderG** [comment]
I have tried with the same text and it seems to work well in Android 5.1.1, 6.x and 7.x.
![image](https://cloud.githubusercontent.com/assets/8654362/25018980/45172d48-2089-11e7-9761-eb583102e0bd.png)

**Comment by GrenderG** [comment]
I'm going to release an update to fix this issue, would you mind waiting some minutes? It'll be available in a moment, the version code will be `1.1.5`.

**Comment by GrenderG** [comment]
Issue solved, sorry for any inconveniences and thanks for reporting! Remember to udpate it: `compile 'com.github.GrenderG:Toasty:1.1.5'`

**Comment by searchy2** [comment]
Wow, nice fix! Thank you so much, now I don't have to use spaces for padding :grin:
