### ISSUE TITLE
Align icon to the right for RTL layouts.

### ISSUE THREAD

**Issue by alirezanazari** [GrenderG/Toasty#19]
Hi, thx for this useful library... How can I change icon position for persian and arabic (rtl text) to right of text?

**Comment by GrenderG** [comment]
It should work fine if your `application` has `android:supportsRtl="true"`. 
See:

![device-2017-04-27-152851](https://cloud.githubusercontent.com/assets/8654362/25485514/8239df38-2b5e-11e7-8a7a-bbe5b291ef36.png)

**Comment by rezasys2** [comment]
I've set supports RTL but still the icon is on left side!

**Comment by GrenderG** [comment]
@rezasys2, this is working fine. Are you using a RTL locale? If not, force it in developer options.
