### ISSUE TITLE
I'm getting error Failed to resolve: com.github.GrednerG:Toasty:1.1.2

### ISSUE THREAD

**Issue by yofu1234** [GrenderG/Toasty#2]
I'm getting error Failed to resolve: com.github.GrednerG:Toasty:1.1.2 whenever I try to build.

Here is my gradle file:
```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
![screen shot 2017-01-21 at 11 17 21 pm](https://cloud.githubusercontent.com/assets/12259153/22179963/384218ba-e030-11e6-86c9-a6a1c8827795.png)

**Comment by akhilnair** [comment]
Please go to File->Settings->Gradle. Uncheck the Offline work if it is checked and sync the project again. It worked for me. Happy coding!

**Comment by GrenderG** [comment]
Try to move `maven { url "https://jitpack.io" }` inside `allprojects > repositories` instead of `buildscript > repositories` and tell me if it works.

**Comment by yofu1234** [comment]
Solved.

**Comment by zubairrahmani** [comment]
> I'm getting error Failed to resolve: com.github.GrednerG:Toasty:1.1.2 whenever I try to build.
> 
> Here is my gradle file:
> 
> ```
> buildscript {
>     repositories {
>         mavenLocal()
>         jcenter()
>         maven { url "https://jitpack.io" }
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:2.1.0'
>         classpath 'com.google.gms:google-services:3.0.0'
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         jcenter()
>     }
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> ```
> 
> ![screen shot 2017-01-21 at 11 17 21 pm](https://cloud.githubusercontent.com/assets/12259153/22179963/384218ba-e030-11e6-86c9-a6a1c8827795.png)

disable this experimental feature from
					File → Settings → Experimental → Gradle → Only sync the active variant
