### ISSUE TITLE
how can i change the font of toast

### ISSUE THREAD

**Issue by alirezanazari** [GrenderG/Toasty#20]
hi how can i change the font (custom) ?

without supportRtl how can i change icon position?

**Comment by GrenderG** [comment]
There's no way to change the font at this moment, I'm using the original Toast's font. I'll study if I add that feature.

Your second question belongs [here](https://github.com/GrenderG/Toasty/issues/19), but as I said the only way to change icon's position is to give your app RTL support.

**Comment by GrenderG** [comment]
@alirezanazari I have added an option to customize every parameter of Toasty.

You can add this (beta) version like so: `compile 'com.github.GrenderG:Toasty:8125e2f'`

Usage:
```java
Toasty.Config.getInstance()
    .setErrorColor(int) // optional
    .setInfoColor(int) // optional
    .setSuccessColor(int) // optional
    .setWarningColor(int) // optional
    .setTextColor(int) // optional
    .setToastTypeface(AssetManager, String) // optional
    .apply(); // required
```
I have to go now, please test it a little bit and give me feedback. If it works correctly I will make the `1.2.0` release.

**Comment by GrenderG** [comment]
Version 1.2.0 has been released, please use it like so:

```gradle
compile 'com.github.GrenderG:Toasty:1.2.0'
```

**Comment by alirezanazari** [comment]
tnx bro
