### ISSUE TITLE
Usage in my app

### ISSUE THREAD

**Issue by FlorentAnders** [GrenderG/Toasty#21]
Hi, I'm using Toasty in my Facebook app Touch for Facebook now, please add it to the list!

http://play.google.com/store/apps/details?id=com.fa.touch.free

**Comment by GrenderG** [comment]
[Done](https://github.com/GrenderG/Toasty/commit/2b15aa0284a654f806c0d903a7fb3cb4f2edc926)! Thanks for using **Toasty**.
