### ISSUE TITLE
Please add my app to the list!

### ISSUE THREAD

**Issue by FlorentAnders** [GrenderG/Toasty#23]
Hello,

please add my news app Daily - News flipped around to the list of apps implementing Toasty. Thanks for your great library!

http://play.google.com/store/apps/details?id=com.fa.daily.free

**Comment by GrenderG** [comment]
Done, thanks for using **Toasty** again. :stuck_out_tongue:

**Comment by FlorentAnders** [comment]
With pleasure:)
