### ISSUE TITLE
How do you adjust the text size?

### ISSUE THREAD

**Issue by martymiller** [GrenderG/Toasty#24]
The text is smaller than the standard Toast.  Is there a way to adjust this?

**Comment by GrenderG** [comment]
Wow, you are right! Thanks for pointing this out. [I have fixed it](https://github.com/GrenderG/Toasty/commit/2e0e46c02dafa7e4c050a772e1ea7f877da90780) and now Toasty's Toasts have the default value ([16sp](https://android.googlesource.com/platform/frameworks/base.git/+/master/core/res/res/values/styles.xml#801)).

Furthermore,  I have added an [option to change the text size](https://github.com/GrenderG/Toasty/blob/master/README.md#configuration).

**Comment by martymiller** [comment]
Thank you!

**Comment by searchy2** [comment]
If it helps, I didn't notice :stuck_out_tongue_winking_eye:
