### ISSUE TITLE
can`t show icon

### ISSUE THREAD

**Issue by FynnJason** [GrenderG/Toasty#25]
To display the usual Toast with icon:

Toasty.normal(yourContext, "Normal toast w/ icon", yourIconDrawable).show();

i use :
Toasty.normal(MainActivity.this, "Icon Toast", R.drawable.ic_check_circle_black_24dp).show();

is the same as : Toasty.normal(MainActivity.this, "Normal Toast").show();

**Comment by GrenderG** [comment]
That's because you are calling 
``` java 
public static Toast normal(@NonNull Context context, @NonNull CharSequence message, int duration)
```
You must pass the `Drawable`, not the resource id.

[Check the sample project!](https://github.com/GrenderG/Toasty/blob/master/app/src/main/java/es/dmoral/toastysample/MainActivity.java#L74-L75)
