### ISSUE TITLE
Can you offer a setter method which can set animation to user?

### ISSUE THREAD

**Issue by Newamber** [GrenderG/Toasty#26]
The default animation is just passable and  I think that will be more delightful if user can set their own animation. Thx~ XD

**Comment by GrenderG** [comment]
I'm using original Toasts in **Toasty** and they are using a system template that can't be changed at all. A solution would be using a custom `View` implementation which resembles to a Toast and then add the custom animations to it, but I wanna keep using the stock Toasts for this library.

TL;DR: **Toasty** uses stock Toasts and animations can't be changed in any way.

**Comment by Newamber** [comment]
Got it~
