### ISSUE TITLE
重复弹出

### ISSUE THREAD

**Issue by xiangxm** [GrenderG/Toasty#3]
hi 博主，这个toast会重复弹出。可以优化一下

**Comment by GrenderG** [comment]
Hello @xiangxm, would you mind to explain your issue in English? I'm afraid I'm not able to understand you.

**Comment by lodgkk** [comment]
His meaning should be, if you click quickly, toast will continue to pop up, the feeling is very poor, you can determine whether there is a change in the contents of the existence of direct

**Comment by GrenderG** [comment]
That's the usual behavior of a Toast, internally it has an stack where Toasts are kept until they can show up. You shouldn't create an app where Toasts are popping constantly, it would be an excess of information; even if you create an app like that, it's good for the user to be able to see all the feedback the app is sending to him.

**Comment by dokiKit** [comment]
if you need debouncing, use rxjava. if you want this behavior on your ui, use rxbinding. For example

```
RxView.clicks(setWallpaperButton)
                .debounce(300,TimeUnit.MILLISECONDS)
                .subscribe { 
                    // show your toast
                }
```

**Comment by xiangxm** [comment]
thanks a lot . :)
