### ISSUE TITLE
How to set custom toast?

### ISSUE THREAD

**Issue by karanthakakr04** [GrenderG/Toasty#30]
```
Toasty.custom(yourContext, "I'm a custom Toast", yourIconDrawable, tintColor, duration, withIcon, 
shouldTint).show();
```
I want to use this to make a custom toast but the problem is I cannot understand what is tintColor here for? is it for the text or background of the toast?
Could you please post an example for clearer understanding?

`Toasty.custom(this, "Success!", R.drawable.ic_check_circle_black_24dp, R.color.white, Toast.LENGTH_SHORT, withIcon, R.color.success).show();`
I have done this so far and stuck with the `withIcon` thing. 

Any help would be appreciated.

**Comment by GrenderG** [comment]
`tintColor` is for the background color; `withIcon` is a boolean used to point out if you want to show the icon you're passing or not.

**Comment by karanthakakr04** [comment]
What is `shouldTint`?

**Comment by GrenderG** [comment]
`shouldTint` is similar to `withIcon`, it's a boolean to point out if you want to tint the Toast with the provided color. You can find examples in the [example app](https://github.com/GrenderG/Toasty/blob/master/app/src/main/java/es/dmoral/toastysample/MainActivity.java).

**Comment by karanthakakr04** [comment]
I faced a problem while running this example but there's a workaround for it. If using this library for Android M and above declare a line like this in your MainActivity:

`int colorCodeSuccess = colorCodeSuccess = ContextCompat.getColor(getApplicationContext(), R.color.success);`

Then declare a custom toast like this in any onClick:

`Toasty.custom(this, "Success!", R.drawable.ic_check_circle_black_24dp, colorCodeSuccess, Toast.LENGTH_SHORT, true, true).show();`

Toasty doesn't directly accept `R.color.success` so I had to find it's workaround. 

I hope this helps for people who are facing this kind of an issue. Thanks!
