### ISSUE TITLE
Toast.LENGTH_LONG does not work on Android 7.1 in onCreate()

### ISSUE THREAD

**Issue by nakawai** [GrenderG/Toasty#33]
Android OS version 7.1

when I call Toasty in onCreate(), Toasty show only 1 sec.
This probrem causes only Android 7.1.
Toast.makeText(LENGTH_LONG).show() works fine.

public class MainActivity extends AppCompatActivity  {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toasty.success(getApplicationContext(), "this toast show only 1 sec",  Toast.LENGTH_LONG).show(); // (A)
            }
        });

        Toasty.success(getApplicationContext(), "this toast show 4 sec", Toast.LENGTH_LONG).show(); // (B)

    }

}

**Comment by GrenderG** [comment]
I don't think that is a Toasty related issue. [This is the method you are calling](https://github.com/GrenderG/Toasty/blob/master/toasty/src/main/java/es/dmoral/toasty/Toasty.java#L127), which [calls this other method](https://github.com/GrenderG/Toasty/blob/master/toasty/src/main/java/es/dmoral/toasty/Toasty.java#L132). And, as you can see [I'm using a normal Toast](https://github.com/GrenderG/Toasty/blob/master/toasty/src/main/java/es/dmoral/toasty/Toasty.java#L199) to set its duration.

Maybe it's something with your app or device. Please review yor code or post more info.

**Comment by nakawai** [comment]
This issue is reproducible with minimum code and Emulator in the following steps:

1. cloning toasty tag 1.2.5
2. modify es.dmoral.toastysample.MainActivity
```
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toasty.error(MainActivity.this, "This is an error toast.", Toast.LENGTH_LONG, true).show(); // add (A)

        findViewById(R.id.button_error_toast).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toasty.error(MainActivity.this, "This is an error toast.", Toast.LENGTH_LONG, true).show(); // modify duration (B)
            }
        });
```
1. run on Emulator api 25(7.1)
1. (A) is shown only 1sec

(A) works fine on Emulator api 24 and 26.

**Comment by arpitnnd** [comment]
Facing the same here on a physical 7.1 device.
Works well on API 26 emulator.

**Comment by GrenderG** [comment]
This is so weird, any idea what might be going on?

**Comment by DdWr** [comment]
Looking into this. I noticed that if I wrap the first `Toasty.error(...)` call in a `OnGlobalLayoutListener` or use a regular `Toast.makeText(...).show()`, it also works fine.

**Comment by frankyxcs** [comment]
Hi DdWR
what do you mean with OnGlobalLayoutListener ? Could you make an example please 

Frank

**Comment by guillermolechuga** [comment]
Hi!

I've been able to workaround it by setting the `Toast.getView()` generated by Toasty on another Toast created with the `makeText()` constructor.

    final Toast toasty = Toasty.error(getContext(), message, Toast.LENGTH_LONG, true);
    final Toast toast = Toast.makeText(getContext(), "", Toast.LENGTH_LONG);
    toast.setView(toasty.getView());
    toast.show();

I believe that the fix on your side can be done by creating the Toast object with the `makeText()` constructor instead of `new Toast()`.

Regards,
Guillermo

**Comment by GrenderG** [comment]
@guillermolechuga I don't really understand why it works, but as you suggested, changing `new Toast()` to `makeText()` apparently solved the issue.

A new update with version `1.2.6` is ready, just wait until [JitPack updates their gradle plugin to 3.0.1](https://twitter.com/GrenderG/status/940224462699597824).

**Comment by GrenderG** [comment]
Update: grab version `1.2.8`, it's working now.

**Comment by GrenderG** [comment]
Is everything working well for u, guys?
