### ISSUE TITLE
How to decrase padding in toast_frame ? 

### ISSUE THREAD

**Issue by kvenkatesh-nyros** [GrenderG/Toasty#34]
I want small toast minimum 7dp padding but not applying in that .where can i change that

**Comment by GrenderG** [comment]
You can't do that, Toasty is using the original 9-patch image as background. You would need to create a custom layout.

**Comment by kvenkatesh-nyros** [comment]
Yes sir i applied custom layout now fine, How can i change position of toast to center
Not working ::Below code not working any alternative methods 
  Toasty toast = Toasty.error(context,context.getResources().getString(R.string.invalidprz), Toast.LENGTH_SHORT);
                    toast.setGravity(Gravity.CENTER, 0, 0);
                    toast.show();
