### ISSUE TITLE
No padding in toasty

### ISSUE THREAD

**Issue by TobiPristupin** [GrenderG/Toasty#36]
Great library, just having an issue with it which I think is a bug. When I create any type of Toasty the text and icon have no right or left padding. Using Android 7.1.1 on API 25.

**Comment by GrenderG** [comment]
Hello, can you provide a screenshot of the issue and the code you are using? Also, has your device Arabic, Hebrew or Persian language (RLT layouts)?

Knowing your device brand would be nice too.

**Comment by TobiPristupin** [comment]
I'm not using RLT layouts, and the device is Xperia Z5.

![unnamed](https://user-images.githubusercontent.com/22137035/29229675-8cb9be5e-7e94-11e7-91d9-85d230316631.png)

That image shows the bug. The code I am using to call the toasty is the following:
`Toasty.success(ForgotPasswordActivity.this, "Recovery email sent", Toast.LENGTH_SHORT).show();`
Inside a class that extends the android support v7 AppCompatActivity.
I tried with warning and error toasties and same result. I haven't changed the library's config.

Surprisingly when I call a similar Toasty in another activity it doesn't happen.
![unnamed 3](https://user-images.githubusercontent.com/22137035/29229850-519840a6-7e95-11e7-8f3f-33a35c37a1fa.png)
Using the exact same code.

When I call a toasty with longer text, the text adjusts correctly, but the icon still has no left padding.
![unnamed 1](https://user-images.githubusercontent.com/22137035/29230004-e6b3ad56-7e95-11e7-94c1-5bf10c4d597a.png)
Using same code on the same activity as the first image.

**Comment by GrenderG** [comment]
It seems that the problem relies on your own code, not in Toasty's one. I think you are overriding some kind of style in that `Activity`, please check that out.

**Comment by searchy2** [comment]
Reminds me of #18 , possibly related?

**Comment by TobiPristupin** [comment]
Yes thank you for pointing that out. I tested with android toast and the issue kept happening. Looks like an android bug. The style I was using was the following

`<style name="LoginTheme" parent="Theme.Design.Light.NoActionBar">
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowTranslucentNavigation">true</item>
        <item name="android:fitsSystemWindows">true</item>
    </style>`

Thanks for your help, I'll close the issue.

**Comment by TobiPristupin** [comment]
Yeah it was the exact same issue as [#18](https://github.com/GrenderG/Toasty/issues/18). Turns out I was using version 1.1.3 so my bad. Upgraded to 1.2.5 and it was fixed (:

**Comment by searchy2** [comment]
Been there done that, thanks to @GrenderG for fixing this issue in Toasty. Interesting note, when using fitsSystemWindows=true in a style, the default Android toast has no paddings either so you HAVE to use Toasty ;)
