### ISSUE TITLE
Gradle fail after adding dependency.

### ISSUE THREAD

**Issue by rohitkhadse** [GrenderG/Toasty#38]
Error:Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (25.3.1) and test app (23.1.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    androidTestCompile 'com.android.support:support-annotations:23.1.1'
    androidTestCompile 'com.android.support.test:runner:0.4.1'
    androidTestCompile 'com.android.support.test:rules:0.4.1'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.1'
    compile 'com.github.GrenderG:Toasty:1.2.5'

}

**Comment by GrenderG** [comment]
This is not an issue directly related to `Toasty` , but just upgrade your annotations version to `25.3.1` or exclude that dependency from `Toasty`:

```
compile('com.github.GrenderG:Toasty:1.2.5') {
    exclude group: 'com.android.support', module: 'support-annotations'
}
```
