### ISSUE TITLE
希望可以定义一个显示位置的参数

### ISSUE THREAD

**Issue by akingyin1987** [GrenderG/Toasty#39]

**Comment by GrenderG** [comment]
You should've opened this issue in English, but according to what I have understood from Google Translate, this issue [has already been answered](https://github.com/GrenderG/Toasty/issues/37).

**Comment by normalhh** [comment]
Hi, would you mind add a method to control toasty gravity? It seems that you suggested to use original Toast to setGravity, but I want to use toasty and place it in the center of activity.

**Comment by iman2420** [comment]
@normalhh Try to use this:

       `fun showErrorToast(context: Context, message: String?) {
        val toast = Toasty.error(context, message.toString(), Toast.LENGTH_SHORT, true)
        toast.view.findViewById<TextView>(R.id.toast_text).gravity = Gravity.CENTER
        toast.show()    }`
