### ISSUE TITLE
Failed to resolve     compile 'com.github.GrenderG:Toasty:1.2.5'

### ISSUE THREAD

**Issue by learnwithprabeesh** [GrenderG/Toasty#41]
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.1'
    compile 'com.github.GrenderG:Toasty:1.2.5'
    testCompile 'junit:junit:4.12'
}

**Comment by ndy1g14** [comment]
in your project gradle put 

```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by mhopmann** [comment]
I had the same problem, when I was setting maven jitpack in buildscript/repositories.
You have to put it in the build.gradle project file, but in allprojects/repositories instead, as explained by @ndy1g14
