### ISSUE TITLE
Toast overlap problem

### ISSUE THREAD

**Issue by DennyWeinberg** [GrenderG/Toasty#43]
The previous toast should be cancelled when a new toast is emitted. The new toast should be displayed immediately instead of cumulating all toasts and times in a "queue".

Could you please fix this? Do you have a workaround for this problem for me?

**Comment by GrenderG** [comment]
That shouldn't be the behavior of Toasts. **Toasty** internally uses [normal Toasts](https://developer.android.com/guide/topics/ui/notifiers/toasts.html).

You can use the [cancel method](https://developer.android.com/reference/android/widget/Toast.html#cancel()) to remove a Toast that is being shown.

**Comment by DennyWeinberg** [comment]
Yes but when using default toasts, I can use a global instance that will timply update the text and reset the time of ONE instance. This is not possible with your library. 

Anyway, thanks for the tip. I will use cancel to help me out.
