### ISSUE TITLE
Can I set the Toast width and height? If not,Can you Support?

### ISSUE THREAD

**Issue by cwyrzz** [GrenderG/Toasty#46]
Can I set the Toast width and height? If not,Can you Support?

**Comment by GrenderG** [comment]
Hello, there is no direct way to do that, but as a workaround you can get the text inside the root `View` and set the width and height there:

```java
Toast toast = Toasty.success(this, "Hi there");
toast.getView().findViewById(R.id.toast_text).setLayoutParams(new LinearLayout.LayoutParams(widht, height));
toast.show();
```

(Or get the root `View` and set padding to it).
