### ISSUE TITLE
Border Color, Thickness etc

### ISSUE THREAD

**Issue by Bennith** [GrenderG/Toasty#5]
Hi @GrenderG

Great plugin you have here, just request if possible to have or assign the toast borders etc
Something like ...

- borderColor (all borders of toast message color)
- borderThickness (all borders of toast message thickness)
- borderLeftColor (left border of toast message color)
- borderLeftThickness (left border of toast message thickness)
- etc

Programmatically

Toasty.custom(yourContext, "I'm a custom Toast", yourIconDrawable, textColor, tintColor, duration, withIcon, borderLeftThickness, borderLeftColor, true).show();

**Comment by GrenderG** [comment]
Answered [here](https://github.com/GrenderG/Toasty/issues/4).
