### ISSUE TITLE
Could not resolve com.github.GrenderG:Toasty:1.2.8

### ISSUE THREAD

**Issue by cv0cv0** [GrenderG/Toasty#51]
Error:Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.github.GrenderG:Toasty:1.2.8.

**Comment by cv0cv0** [comment]
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.GrenderG:Toasty:1.2.8.

Could not resolve com.github.GrenderG:Toasty:1.2.8.
Required by:
    project :app
 > Could not resolve com.github.GrenderG:Toasty:1.2.8.
    > Could not get resource 'https://jitpack.io/com/github/GrenderG/Toasty/1.2.8/Toasty-1.2.8.pom'.
          > Could not GET 'https://jitpack.io/com/github/GrenderG/Toasty/1.2.8/Toasty-1.2.8.pom'. Received status code 403 from server: Forbidden

**Comment by GrenderG** [comment]
Can you share your project's `build.gradle` file and your module's (app) `build.gradle` file?

**Comment by cv0cv0** [comment]
Yes, the doubt is the server problem. It used to be good. Yesterday, the reloading system met this problem, and then it was good in the afternoon.

可以了，怀疑是服务器问题。以前是好的，昨天重装系统遇到这个问题，然后下午又好了。

**Comment by cv0cv0** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.studio_version='3.0.1'
    ext.kotlin_version = '1.2.10'
    ext.anko_version='0.10.1'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$studio_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by cv0cv0** [comment]
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "com.google.android"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        kapt {
            arguments {
                arg('eventBusIndex', 'com.google.android.EventBusIndex')
            }
        }
    }
    dataBinding {
        enabled true
    }
    androidExtensions {
        experimental = true
    }
    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            signingConfig signingConfigs.sign
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            android.applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "WMS_v${variant.versionName} (Build ${variant.versionCode}).apk"
                }
            }
        }
        debug {
            signingConfig signingConfigs.sign
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation "org.jetbrains.anko:anko-commons:$anko_version"
    kapt "com.android.databinding:compiler:$studio_version"
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.2.0'
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.0.0'
    implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.4@aar'
    implementation 'com.trello.rxlifecycle2:rxlifecycle:2.2.0'
    implementation 'com.trello.rxlifecycle2:rxlifecycle-components:2.2.0'
    implementation 'com.trello.rxlifecycle2:rxlifecycle-kotlin:2.2.0'
    implementation 'com.squareup.okhttp3:okhttp:3.9.0'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.google.code.gson:gson:2.8.1'
    implementation 'org.greenrobot:eventbus:3.1.1'
    kapt 'org.greenrobot:eventbus-annotation-processor:3.1.1'
    implementation 'com.google.zxing:core:3.3.0'
    implementation 'cn.bingoogolapple:bga-qrcodecore:1.1.9@aar'
    implementation 'cn.bingoogolapple:bga-zxing:1.1.9@aar'
    implementation 'com.github.GrenderG:Toasty:1.2.8'
}

**Comment by cv0cv0** [comment]
Give others a reference.

**Comment by GrenderG** [comment]
I have just tried and it works fine for me, also your code looks good. Is the error still there?

**Comment by cv0cv0** [comment]
It's good that afternoon. Skepticism is a server problem.

**Comment by arbazalam2z** [comment]
Today I am facing the same issue.
