### ISSUE TITLE
after adding your library in project these errors come up

### ISSUE THREAD

**Issue by tjnapster555** [GrenderG/Toasty#53]
build error
```java
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]
C:\Users\tariq\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\d8468f24b31c24ee8d29575dc26584f6\res\values-v26\values-v26.xml
Error:(9, 5) error: resource android:attr/colorError not found.
Error:(13, 5) error: resource android:attr/colorError not found.
Error:(17, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
C:\Users\tariq\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\d8468f24b31c24ee8d29575dc26584f6\res\values\values.xml
Error:(252, 5) error: resource android:attr/fontStyle not found.
Error:(252, 5) error: resource android:attr/font not found.
Error:(252, 5) error: resource android:attr/fontWeight not found.
C:\Users\tariq\Desktop\adnan laravel android pharamacy\materiallogindemo-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml
Error:(7) resource android:attr/colorError not found.
Error:(11) resource android:attr/colorError not found.
Error:(15) style attribute 'android:attr/keyboardNavigationCluster' not found.
C:\Users\tariq\Desktop\adnan laravel android pharamacy\materiallogindemo-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Error:(438) resource android:attr/fontStyle not found.
Error:(438) resource android:attr/font not found.
Error:(438) resource android:attr/fontWeight not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
Information:BUILD FAILED in 13s
Information:17 errors
Information:0 warnings
Information:See complete output in console
```

**Comment by GrenderG** [comment]
I don't think this issue is directly related to Toasty. Have you tried invalidating cache and restarting Android Studio?

**Comment by tjnapster555** [comment]
@GrenderG  yes i try to rebuild the project also clean the project restart android studio too nothing works but when i add the library android studio give me error on this 
   compile  'com.android.support:appcompat-v7:25.4.0'
but when i remove the toasty lbrary  then no error comes up

**Comment by tjnapster555** [comment]
![image](https://user-images.githubusercontent.com/12066009/34578316-4a351a58-f1a6-11e7-86bd-80792acda041.png)
@GrenderG

**Comment by GrenderG** [comment]
I'm not talking about rebuild / clean, I'm talking about `File > Invalidate Caches / Restart...`.

**Comment by GrenderG** [comment]
Why don't you use the latest version? (`27.0.02`)

**Comment by tjnapster555** [comment]
i try 
 compile  'com.android.support:appcompat-v7:25.4.0'
    compile 'com.android.support:design:25.4.0'
but then i get error on  this  compile 'com.android.support:design:25.4.0'

**Comment by tjnapster555** [comment]
@GrenderG is your library support the older version if i use the old version of your library ?

**Comment by GrenderG** [comment]
As I said, try to use the latest version. However, this problem is not related to Toasty; a quick look around tells you [how to solve it](https://stackoverflow.com/questions/42374151/all-com-android-support-libraries-must-use-the-exact-same-version-specification). :stuck_out_tongue_winking_eye:

**Comment by tjnapster555** [comment]
well if anyone else has this problem then the solution is to use the old version of Toasty 
i use this  compile 'com.github.GrenderG:Toasty:1.2.5'

**Comment by GrenderG** [comment]
@tjnapster555 even if that solves this specific issue, that's not a good solution. [This is](https://stackoverflow.com/a/42374426/4208583).
