### ISSUE TITLE
Crash in ToastyUtils.getDrawable

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [GrenderG/Toasty#59]
Got this exception from crash reporting in my app:
```
java.lang.NullPointerException: Attempt to invoke virtual method  'android.graphics.drawable.Drawable android.content.Context.getDrawable(int)' on  a null object reference
     at  es.dmoral.toasty.ToastyUtils.getDrawable(ToastyUtils.java:53)
     at  es.dmoral.toasty.Toasty.info(Toasty.java:116)
     at  es.dmoral.toasty.Toasty.info(Toasty.java:106)
```

**Comment by GrenderG** [comment]
This seems a problem related to the `Context` you are using in your app, **Toasty** only uses it dynamically to get resources. Thanks for reporting anyway, have you experienced more `NullPointerException`s in your app?

**Comment by GrenderG** [comment]
Gonna close this as there is no more feedback.

**Comment by ZimM-LostPolygon** [comment]
Thing is, the app was running for a few days, happily showing toasts. And then suddenly I got this crash. This is the one and only case of this crash I got in over a month.

**Comment by qinyang1018** [comment]
@GrenderG  I also met the same problem
![image](https://user-images.githubusercontent.com/15726024/44638478-9958ae00-a9e9-11e8-95fa-97b17beba51f.png)
