### ISSUE TITLE
NullPointException shows when I make a toast

### ISSUE THREAD

**Issue by EricZX123** [GrenderG/Toasty#60]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
at android.widget.ToastInjector.addAppName(ToastInjector.java:50)
at android.widget.Toast.makeText(Toast.java:269)
at es.dmoral.toasty.Toasty.custom(Toasty.java:171)
at es.dmoral.toasty.Toasty.warning(Toasty.java:100)

**Comment by GrenderG** [comment]
Can you provide more context?

**Comment by EricZX123** [comment]
I tested my app on other android devices,I found  it only shown on MIUI(made by XiaoMi) ,and  was a system problem.

**Comment by lintax** [comment]
a chance to release a new version in order to replace copied-and-patched-code by the library link?
it is the most common crash cause currently (about 7-8 crashes per 1000 unique users)

**Comment by GrenderG** [comment]
@lintax Done, use version `1.3.0`.

**Comment by lintax** [comment]
thanks
