### ISSUE TITLE
how can i change the color of a custom toast 

### ISSUE THREAD

**Issue by kingofkech** [GrenderG/Toasty#61]
i am using your library and i want to create the same effect as the kill -9 everyone toast you are using but i can not seem to find any kind of way to change the color of the custom font.

Thank you

**Comment by GrenderG** [comment]
Next time look at the [examples](https://github.com/GrenderG/Toasty/blob/master/app/src/main/java/es/dmoral/toastysample/MainActivity.java#L87-L93). 😊
