### ISSUE TITLE
Toasty - show message from resource

### ISSUE THREAD

**Issue by Bramengton** [GrenderG/Toasty#67]
Android Toast can use string resources without converting to CharSequence or String:
Toast.makeText(context, **R.string.connection_lost**, Toast.LENGTH_SHORT).show();
in Toasty only this way:
Toasty.error(context, **context.getString(R.string.connection_lost)**, Toast.LENGTH_SHORT, true).show();
Add the ability to use string resources without converting!

**Comment by anandkumarkparmar** [comment]
Hi @GrenderG, I would love to work on this, if no one has started yet. Can I take it up?

Thanks

**Comment by anandkumarkparmar** [comment]
Thanks @GrenderG.

**Comment by anandkumarkparmar** [comment]
Hi @GrenderG, I have created a PR. Please review it if possible. Thanks.

**Comment by GrenderG** [comment]
Added [here](https://github.com/GrenderG/Toasty/commit/6724d40698b2e1c942fc42039dc210192ce8e8f3), a new version will be released soon.
