### ISSUE TITLE
AndroidManifest.xml application label

### ISSUE THREAD

**Issue by franciscoaleixo** [GrenderG/Toasty#7]
Hi, is there any specific reason as to why android:label is used in the library? I'm asking since it causes conflicts when merging the AndroidManifests.

Now, I know there's workarounds (like using tools:replace) but if it's not needed, could you remove it? It just adds unnecessary clutter.

Thanks in advance :+1:

**Comment by GrenderG** [comment]
You are right, I will check it.

**Comment by GrenderG** [comment]
Solved in v. 1.1.3.
