### ISSUE TITLE
Toasty is being used in Wakification

### ISSUE THREAD

**Issue by koenschauwaert** [GrenderG/Toasty#71]
I am using Toasty in my app 'Wakification'.
Link: 
https://play.google.com/store/apps/details?id=nl.overnightprojects.wakification

Thanks for adding and the great work! Works flawlessly - have been using custom snackbars (also a library) before, but it lags/shows slowly sometimes. Regular toasts are great and once build they show and keep on top, even if the activity finishes. Yours are even better thanks to customisation! Thanks!

**Comment by GrenderG** [comment]
Added!
