### ISSUE TITLE
Nothing is show Samsung Mobile 

### ISSUE THREAD

**Issue by ajayqualwebs** [GrenderG/Toasty#72]
This is my code

Toasty.info(context, Common.getResourceString(context, "Enter User Name"), Toast.LENGTH_SHORT).show();

Nothing is showing in Samsung Galaxy J7 Pro mobile

**Comment by GrenderG** [comment]
This seems to be a Samsung related issue. What happens if you try to show an standard Toast? Does it work well?

In case it works well, try to create a Toast and [change its layout](https://stackoverflow.com/a/11288522/4208583) to see what happens.

**Comment by GrenderG** [comment]
Closing this as I haven't received feedback from @ajayqualwebs.
