### ISSUE TITLE
About Licence

### ISSUE THREAD

**Issue by AcnNuriSezgin** [GrenderG/Toasty#73]
Our project manager worried about your library's license strategy. We used Toasty as a normal Toast message shower, no extends, no implements, no other customizations. 

Could you explain to us is there any problem here?
Do we have to show your library name and author in anywhere inside of application?

Thanks.

**Comment by GrenderG** [comment]
Short answer: No, although I'd love it.

Long answer: No, but LGPL has some issues regarding its use in Android libraries and I'm working on another license intended to use in these cases, called [Libcense](https://github.com/GrenderG/Libcense-1.0). I'm trying to get some feedback (tell your project manager to give it a look :stuck_out_tongue_closed_eyes:) and, when it's ready, use it in my projects, including **Toasty**.
