### ISSUE TITLE
Is there any consideration of using a singleton toast

### ISSUE THREAD

**Issue by cronusaswang** [GrenderG/Toasty#77]
Is there any consideration of using a singleton toast

**Comment by cronusaswang** [comment]
static Toast currentToast;
 and then write in method custom（。。。）{
if (currentToast==null){
            currentToast = Toast.makeText(context, "", duration);
   }
}

is that ok?

**Comment by GrenderG** [comment]
Sorry, this is not a Toasty related issue.
