### ISSUE TITLE
Toasty usage in my app.

### ISSUE THREAD

**Issue by Bramengton** [GrenderG/Toasty#78]
Hi, i am using Toasty lib in my app.
name: Caller+
link: https://play.google.com/store/apps/details?id=com.mphone.callerplus
logo: https://lh3.googleusercontent.com/2HGejlGZgASHaLFdgeCjK3wbvRGn-CSdXuAUN3E8dzK61usHjn8TKTxR_V160avI-js7=s180-rw
Thank you.

**Comment by GrenderG** [comment]
Sorry for the long delay, it has been added.
