### ISSUE TITLE
Using in my app

### ISSUE THREAD

**Issue by trivisionzero** [GrenderG/Toasty#8]
So I just published an update to my app, ChromoPhoto, and included your Toasty project! When in the app, it shows snackbars for most notifications, and out of the app, the customized Toastys.

I also have one in-app Toasty for the set image quality dialog.

You said to post an issue if an app is using your Toasty, so here I am :D
I also plan on using them more, and even adding them to my app, Get Assistant if I have time.

Also, thanks for the gorgeous customized toasts, they look great!

Here's my app: https://play.google.com/store/apps/details?id=com.trivisionzero.chromophoto

The latest update is 1.5, I just published it, so it may take a while to roll out everywhere.

**Comment by GrenderG** [comment]
Thanks for using Toasty, [here is](https://github.com/GrenderG/Toasty/commit/908e9710dd164b3fd63bd04731301d06c850e7da) your app. 😀

**Comment by creati8e** [comment]
I use Toasty too! My app called AutoTagger https://play.google.com/store/apps/details?id=com.serg.chuprin.tageditor

**Comment by GrenderG** [comment]
@creati8e Your app has been added. ^^
