### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 2318423730** [GrenderG/Toasty#81]
java.lang.NoSuchFieldError: No static field toast_icon of type I in class Les/dmoral/toasty/R$id; or its superclasses (declaration of 'es.dmoral.toasty.R$id' appears in /data/app/

error in:
  ImageView toastIcon = (ImageView)toastLayout.findViewById(id.toast_icon);

**Comment by GrenderG** [comment]
Can you provide more info? Are you using proguard? Do you have any resource with the same name as `toast_icon`? That error usually means duplicate resource names.
