### ISSUE TITLE
How to let it show more longer ?

### ISSUE THREAD

**Issue by sendtion** [GrenderG/Toasty#9]
怎么显示Toast时间更长呢？貌似设置了无效，看了源码没使用时间设置？

**Comment by GrenderG** [comment]
You can't as this library is built upon the original Toast of Android, which uses 0 and 1 flags for [SHORT](https://developer.android.com/reference/android/widget/Toast.html#LENGTH_SHORT) and [LONG](https://developer.android.com/reference/android/widget/Toast.html#LENGTH_LONG) duration.

My plan for now is to respect those durations, but there are some workarounds to make a Toast "show up" for longer.

- [Workaround 1](http://stackoverflow.com/questions/2220560/can-an-android-toast-be-longer-than-toast-length-long)
- [Workaround 2](http://stackoverflow.com/questions/14503727/how-can-i-show-a-toast-for-a-specific-duration)
